#!perl

use 5.010001;
use strict;
use warnings;

# DATE
# VERSION

use Perinci::CmdLine::Any;

my $prefix = '/App/fiatx/';

Perinci::CmdLine::Any->new(
    url => $prefix,
    log => 1,
    subcommands => {
        'spot-rate'      => {url => "${prefix}spot_rate"},
        'all-spot-rates' => {url => "${prefix}all_spot_rates"},
        'sources'        => {url => "${prefix}sources"},
    },
)->run;

# ABSTRACT: Fiat currency exchange rate tool
# PODNAME:

=head1 SYNOPSIS

First, create a MySQL database e.g. C<fiatx>. Then in F<~/.config/fiatx.conf>:

 db_name=fiatx
 ; the app can also look for passwords in my.cnf
 ; db_username=...
 ; db_password=...

To get conversion rates of USD/IDR (by default the dealer's 'sell' rate):

 % fiatx spot-rate USD IDR

By default result is cached for 4 hours, to force querying from the source
again:

 % fiatx spot-rate USD IDR --no-cache

To get dealer's 'buy' rate:

 % fiatx spot-rate USD IDR --type buy

To query from a specific source:

 % fiatx spot-rate USD IDR --source bi

To get highest/lowest rate of all sources:

 % fiatx spot-rate USD IDR --source :highest
 % fiatx spot-rate USD IDR --source :lowest

To get rate from source with the newest/oldest update:

 % fiatx spot-rate USD IDR --source :newest
 % fiatx spot-rate USD IDR --source :oldest

To get rate averaged from several sources:

 % fiatx spot-rate USD IDR --source :average

To list available sources:

 % fiatx sources

To get all spot rates from a source:

 % fiatx all-spot-rates bca

For more details, use C<fiatx --help> or consult documentation.


=head1 DESCRIPTION
