#!perl

use 5.010001;
use strict;
use warnings;

# DATE
# VERSION

use Perinci::CmdLine::Any;

my $prefix = '/App/fiatx/';

Perinci::CmdLine::Any->new(
    url => $prefix,
    log => 1,
    subcommands => {
        'spot-rates'     => {url => "${prefix}spot_rates"},
        'sources'        => {url => "${prefix}sources"},
    },
)->run;

# ABSTRACT: Fiat currency exchange rate tool
# PODNAME:

=head1 SYNOPSIS

First, create a MySQL database e.g. C<fiatx>. Then in F<~/.config/fiatx.conf>:

 db_name=fiatx
 ; the app can also look for passwords in my.cnf
 ; db_username=...
 ; db_password=...

To see all conversion rates for all pairs and all sources (possible huge list
and takes a long time):

 % fiatx spot-rates

To see conversion rates for all pairs from a single source e.g. C<bca> (note:
not all sources might support this):

 % fiatx spot-rates bca

To list available sources:

 % fiatx sources

To see conversion rates for a single pair and type from a single source e.g.
C<bca>:

 % fiatx spot-rates bca USD/IDR sell

By default result is cached in database for a few hours. To force fetching from
remote source again:

 % fiatx spot-rate bca USD/IDR sell --no-cache

To get another type:

 % fiatx spot-rate bca USD/IDR buy

To get highest/lowest rate of all sources:

 % fiatx spot-rate :highest USD/IDR
 % fiatx spot-rate :lowest  USD/IDR

To get rate from source with the newest/oldest update:

 % fiatx spot-rate :newest USD/IDR
 % fiatx spot-rate :oldest USD/IDR

To get rate averaged from several sources:

 % fiatx spot-rate :average USD/IDR

For more details, use C<fiatx --help> or consult documentation.


=head1 DESCRIPTION
