#!perl

use 5.010001;
use strict;
use warnings;

# DATE
# VERSION

use Perinci::CmdLine::Any;

Perinci::CmdLine::Any->new(
    url => "/App/fiatx/fiatx",
    log => 1,
)->run;

# ABSTRACT: Currency exchange rate tool
# PODNAME:

=head1 SYNOPSIS

First, create a MySQL database e.g. C<fiatx>. Then in F<~/.config/fiatx.conf>:

 db_name=fiatx
 ; the app can also look for passwords in my.cnf
 ; db_username=...
 ; db_password=...

 ; optional. this way, you can just specify USD instead of USD/IDR
 ;default_quote_currency=IDR

Then:

 # Check USD/IDR rates from any source
 % fiatx USD/IDR
 % fiatx usd      ;# works, if you have set default_quote_currency to IDR

 # Check rate from specific source(s) only
 % fiatx usd -s bca
 % fiatx usd -s bca -s bi

 # Check rate and prefer specific types only (in this case: bank notes)
 % fiatx usd -t bn

 # Check rates of all known pairs from all sources (possible huge list and takes
 # a long time, turn on --trace to see progress):
 % fiatx --all-pairs --trace

 # See available sources
 % fiatx -l


=head1 DESCRIPTION
